import 'package:flutter/material.dart';

/// One emoji plus the text used for searching it.
class EmojiData {
  const EmojiData(
    this.emoji,
    this.name, {
    this.keywords = const <String>[],
    this.skinnable = false,
  });

  /// The emoji characters (may be a ZWJ sequence).
  final String emoji;

  /// Short CLDR-style name (lowercase words).
  final String name;

  /// Extra search terms (synonyms, categories).
  final List<String> keywords;

  /// Whether a skin-tone modifier can be appended to this emoji.
  final bool skinnable;

  /// All tokens matched by the search field.
  String get searchText {
    final StringBuffer buffer = StringBuffer(name);
    for (final String keyword in keywords) {
      buffer.write(' $keyword');
    }
    return buffer.toString();
  }
}

/// A tab of the emoji panel, mirroring WhatsApp's category bar.
enum EmojiCategory {
  smileys('Smileys', Icons.emoji_emotions_outlined, _smileys),
  gestures('Gestures & people', Icons.waving_hand_outlined, _gestures),
  animals('Animals & nature', Icons.pets_outlined, _animals),
  food('Food & drink', Icons.restaurant_outlined, _food),
  activities('Activities', Icons.sports_soccer_outlined, _activities),
  travel('Travel & places', Icons.flight_outlined, _travel),
  objects('Objects', Icons.lightbulb_outlined, _objects),
  symbols('Symbols', Icons.favorite_outline, _symbols),
  flags('Flags', Icons.flag_outlined, _flags);

  const EmojiCategory(this.label, this.icon, this.emojis);

  final String label;
  final IconData icon;
  final List<EmojiData> emojis;
}

const List<EmojiData> _smileys = <EmojiData>[
  EmojiData('😀', 'grinning face'),
  EmojiData('😃', 'grinning face with big eyes'),
  EmojiData('😄', 'grinning face with smiling eyes'),
  EmojiData('😁', 'beaming face with smiling eyes'),
  EmojiData('😆', 'grinning squinting face'),
  EmojiData('😅', 'grinning face with sweat'),
  EmojiData('🤣', 'rolling on the floor laughing', keywords: <String>['rofl', 'lol']),
  EmojiData('😂', 'face with tears of joy', keywords: <String>['lol', 'crying']),
  EmojiData('🙂', 'slightly smiling face'),
  EmojiData('🙃', 'upside-down face'),
  EmojiData('😉', 'winking face'),
  EmojiData('😊', 'smiling face with smiling eyes', keywords: <String>['blush']),
  EmojiData('😇', 'smiling face with halo', keywords: <String>['angel']),
  EmojiData('🥰', 'smiling face with hearts'),
  EmojiData('😍', 'smiling face with heart-eyes', keywords: <String>['love']),
  EmojiData('🤩', 'star-struck', keywords: <String>['eyes', 'sparkle']),
  EmojiData('😘', 'face blowing a kiss'),
  EmojiData('😗', 'kissing face'),
  EmojiData('😚', 'kissing face with closed eyes'),
  EmojiData('😋', 'face savoring food', keywords: <String>['yum']),
  EmojiData('😛', 'face with tongue'),
  EmojiData('😜', 'winking face with tongue'),
  EmojiData('🤪', 'zany face', keywords: <String>['crazy']),
  EmojiData('😝', 'squinting face with tongue'),
  EmojiData('🤗', 'hugging face', keywords: <String>['hug']),
  EmojiData('🤭', 'face with hand over mouth', keywords: <String>['shhh']),
  EmojiData('🤫', 'shushing face', keywords: <String>['quiet', 'shhh']),
  EmojiData('🤔', 'thinking face', keywords: <String>['hmm']),
  EmojiData('🤨', 'face with raised eyebrow'),
  EmojiData('😐', 'neutral face'),
  EmojiData('😑', 'expressionless face'),
  EmojiData('😶', 'face without mouth'),
  EmojiData('😏', 'smirking face'),
  EmojiData('😒', 'unamused face'),
  EmojiData('🙄', 'face with rolling eyes'),
  EmojiData('😬', 'grimacing face', keywords: <String>['awkward']),
  EmojiData('😮', 'face with open mouth', keywords: <String>['surprised']),
  EmojiData('😯', 'hushed face'),
  EmojiData('😲', 'astonished face', keywords: <String>['shocked']),
  EmojiData('😳', 'flushed face', keywords: <String>['embarrassed']),
  EmojiData('🥺', 'pleading face', keywords: <String>['puppy']),
  EmojiData('😢', 'crying face'),
  EmojiData('😭', 'loudly crying face', keywords: <String>['sob']),
  EmojiData('😤', 'face with steam from nose', keywords: <String>['angry']),
  EmojiData('😠', 'angry face'),
  EmojiData('🤬', 'face with symbols on mouth', keywords: <String>['swearing', 'cursing']),
  EmojiData('😡', 'pouting face'),
  EmojiData('🤯', 'exploding head', keywords: <String>['mind blown']),
  EmojiData('😱', 'face screaming in fear', keywords: <String>['scared']),
  EmojiData('🥶', 'cold face', keywords: <String>['freezing']),
  EmojiData('🥵', 'hot face', keywords: <String>['sweating']),
  EmojiData('🤢', 'nauseated face', keywords: <String>['sick']),
  EmojiData('🤮', 'face vomiting', keywords: <String>['sick']),
  EmojiData('🤧', 'sneezing face', keywords: <String>['sick']),
  EmojiData('😷', 'face with medical mask', keywords: <String>['mask', 'sick']),
  EmojiData('🤒', 'face with thermometer', keywords: <String>['sick']),
  EmojiData('🤕', 'face with head-bandage'),
  EmojiData('🤑', 'money-mouth face'),
  EmojiData('🤠', 'cowboy hat face'),
  EmojiData('😈', 'smiling face with horns', keywords: <String>['devil']),
  EmojiData('👿', 'angry face with horns'),
  EmojiData('👻', 'ghost'),
  EmojiData('💀', 'skull', keywords: <String>['death']),
  EmojiData('☠️', 'skull and crossbones'),
  EmojiData('🤖', 'robot'),
  EmojiData('👽', 'alien'),
  EmojiData('🎃', 'jack-o-lantern', keywords: <String>['halloween']),
  EmojiData('😺', 'grinning cat'),
  EmojiData('😸', 'grinning cat with smiling eyes'),
  EmojiData('😹', 'cat with tears of joy'),
  EmojiData('😻', 'smiling cat with heart-eyes'),
  EmojiData('😼', 'cat with wry smile'),
  EmojiData('😽', 'kissing cat'),
  EmojiData('🙀', 'weary cat'),
  EmojiData('😿', 'crying cat'),
  EmojiData('😾', 'pouting cat'),
  EmojiData('💋', 'kiss mark', keywords: <String>['lips']),
  EmojiData('💌', 'love letter'),
  EmojiData('💘', 'heart with arrow'),
  EmojiData('💝', 'heart with ribbon'),
  EmojiData('💖', 'sparkling heart'),
  EmojiData('💗', 'growing heart'),
  EmojiData('💓', 'beating heart'),
  EmojiData('💞', 'revolving hearts'),
  EmojiData('💕', 'two hearts'),
  EmojiData('💟', 'heart decoration'),
  EmojiData('❣️', 'heart exclamation'),
  EmojiData('💔', 'broken heart', keywords: <String>['sad']),
  EmojiData('❤️', 'red heart', keywords: <String>['love']),
  EmojiData('🧡', 'orange heart'),
  EmojiData('💛', 'yellow heart'),
  EmojiData('💚', 'green heart'),
  EmojiData('💙', 'blue heart'),
  EmojiData('💜', 'purple heart'),
  EmojiData('🤎', 'brown heart'),
  EmojiData('🖤', 'black heart'),
  EmojiData('🤍', 'white heart'),
];

const List<EmojiData> _gestures = <EmojiData>[
  EmojiData('👋', 'waving hand', keywords: <String>['hello', 'bye'], skinnable: true),
  EmojiData('🤚', 'raised back of hand', skinnable: true),
  EmojiData('🖐️', 'hand with fingers splayed', skinnable: true),
  EmojiData('✋', 'raised hand', keywords: <String>['stop'], skinnable: true),
  EmojiData('🖖', 'vulcan salute', skinnable: true),
  EmojiData('👌', 'OK hand', skinnable: true),
  EmojiData('🤌', 'pinched fingers', keywords: <String>['italian'], skinnable: true),
  EmojiData('🤏', 'pinching hand', skinnable: true),
  EmojiData('✌️', 'victory hand', keywords: <String>['peace'], skinnable: true),
  EmojiData('🤞', 'crossed fingers', keywords: <String>['luck'], skinnable: true),
  EmojiData('🤟', 'love-you gesture', skinnable: true),
  EmojiData('🤘', 'sign of the horns', keywords: <String>['rock'], skinnable: true),
  EmojiData('🤙', 'call me hand', skinnable: true),
  EmojiData('👈', 'backhand index pointing left', skinnable: true),
  EmojiData('👉', 'backhand index pointing right', skinnable: true),
  EmojiData('👆', 'backhand index pointing up', skinnable: true),
  EmojiData('🖕', 'middle finger', keywords: <String>['flip'], skinnable: true),
  EmojiData('👇', 'backhand index pointing down', skinnable: true),
  EmojiData('☝️', 'index pointing up', skinnable: true),
  EmojiData('👍', 'thumbs up', keywords: <String>['like', 'good'], skinnable: true),
  EmojiData('👎', 'thumbs down', keywords: <String>['dislike'], skinnable: true),
  EmojiData('✊', 'raised fist', skinnable: true),
  EmojiData('👊', 'oncoming fist', keywords: <String>['punch'], skinnable: true),
  EmojiData('🤛', 'left-facing fist', skinnable: true),
  EmojiData('🤜', 'right-facing fist', skinnable: true),
  EmojiData('👏', 'clapping hands', keywords: <String>['applause'], skinnable: true),
  EmojiData('🙌', 'raising hands', keywords: <String>['celebrate'], skinnable: true),
  EmojiData('👐', 'open hands', skinnable: true),
  EmojiData('🤲', 'palms up together', keywords: <String>['prayer'], skinnable: true),
  EmojiData('🤝', 'handshake', keywords: <String>['deal'], skinnable: true),
  EmojiData('🙏', 'folded hands', keywords: <String>['please', 'thank you', 'pray'], skinnable: true),
  EmojiData('✍️', 'writing hand', keywords: <String>['note'], skinnable: true),
  EmojiData('💅', 'nail polish', keywords: <String>['manicure'], skinnable: true),
  EmojiData('🤳', 'selfie', skinnable: true),
  EmojiData('💪', 'flexed biceps', keywords: <String>['muscle', 'strong'], skinnable: true),
  EmojiData('🦾', 'mechanical arm', keywords: <String>['robot']),
  EmojiData('🦿', 'mechanical leg'),
  EmojiData('🦵', 'leg', skinnable: true),
  EmojiData('🦶', 'foot', skinnable: true),
  EmojiData('👂', 'ear', keywords: <String>['hearing'], skinnable: true),
  EmojiData('👃', 'nose', skinnable: true),
  EmojiData('🧠', 'brain'),
  EmojiData('🫀', 'anatomical heart'),
  EmojiData('🫁', 'lungs'),
  EmojiData('🦷', 'tooth'),
  EmojiData('🦴', 'bone'),
  EmojiData('👀', 'eyes', keywords: <String>['look']),
  EmojiData('👁️', 'eye'),
  EmojiData('👅', 'tongue'),
  EmojiData('👄', 'mouth', keywords: <String>['lips']),
  EmojiData('🫦', 'biting lip'),
  EmojiData('👶', 'baby', skinnable: true),
  EmojiData('🧒', 'child', skinnable: true),
  EmojiData('👦', 'boy', skinnable: true),
  EmojiData('👧', 'girl', skinnable: true),
  EmojiData('🧑', 'person', skinnable: true),
  EmojiData('👨', 'man', skinnable: true),
  EmojiData('👩', 'woman', skinnable: true),
  EmojiData('🧓', 'older person', skinnable: true),
  EmojiData('👴', 'old man', skinnable: true),
  EmojiData('👵', 'old woman', skinnable: true),
  EmojiData('🧑‍🦱', 'person with curly hair', keywords: <String>['curls'], skinnable: false),
  EmojiData('👨‍🦰', 'man with red hair', keywords: <String>['ginger'], skinnable: false),
  EmojiData('👩‍🦳', 'woman with white hair', skinnable: false),
  EmojiData('👲', 'person with skullcap', keywords: <String>['guan'], skinnable: true),
  EmojiData('🧕', 'woman with headscarf', keywords: <String>['hijab'], skinnable: true),
  EmojiData('👮', 'police officer', keywords: <String>['cop'], skinnable: true),
  EmojiData('🕵️', 'detective', keywords: <String>['spy'], skinnable: true),
  EmojiData('💂', 'guard', keywords: <String>['palace'], skinnable: true),
  EmojiData('👷', 'construction worker', keywords: <String>['hard hat'], skinnable: true),
  EmojiData('🤴', 'prince', skinnable: true),
  EmojiData('👸', 'princess', skinnable: true),
  EmojiData('👳', 'person wearing turban', skinnable: true),
  EmojiData('🙋', 'person raising hand', keywords: <String>['me'], skinnable: true),
  EmojiData('🤦', 'person facepalming', keywords: <String>['facepalm'], skinnable: true),
  EmojiData('🤷', 'person shrugging', keywords: <String>['shrug'], skinnable: true),
  EmojiData('💆', 'person getting massage', skinnable: true),
  EmojiData('💇', 'person getting haircut', skinnable: true),
  EmojiData('🏃', 'person running', keywords: <String>['runner'], skinnable: true),
  EmojiData('🚶', 'person walking', skinnable: true),
  EmojiData('🧍', 'person standing', skinnable: true),
  EmojiData('🧎', 'person kneeling', skinnable: true),
  EmojiData('🏄', 'person surfing', keywords: <String>['surf'], skinnable: true),
  EmojiData('🚣', 'person rowing boat', skinnable: true),
  EmojiData('🧗', 'person climbing', skinnable: true),
  EmojiData('🤸', 'person cartwheeling', skinnable: true),
  EmojiData('🤼', 'people wrestling', skinnable: false),
  EmojiData('🤾', 'person playing handball', skinnable: true),
  EmojiData('🧘', 'person in lotus position', keywords: <String>['yoga', 'meditation'], skinnable: true),
  EmojiData('🏇', 'horse racing', skinnable: true),
  EmojiData('🚴', 'person biking', skinnable: true),
  EmojiData('🚵', 'person mountain biking', skinnable: true),
  EmojiData('🤺', 'person fencing'),
  EmojiData('⛹️', 'person bouncing ball', skinnable: true),
  EmojiData('🏌️', 'person golfing', skinnable: true),
  EmojiData('🏋️', 'person lifting weights', skinnable: true),
  EmojiData('🛀', 'person taking bath', skinnable: true),
  EmojiData('🛌', 'person in bed', skinnable: true),
  EmojiData('👼', 'baby angel', keywords: <String>['cherub'], skinnable: true),
  EmojiData('🎅', 'Santa Claus', keywords: <String>['christmas'], skinnable: true),
  EmojiData('🤶', 'Mrs. Claus', keywords: <String>['christmas'], skinnable: true),
  EmojiData('🦸', 'superhero', skinnable: true),
  EmojiData('🦹', 'supervillain', skinnable: true),
  EmojiData('🧙', 'mage', keywords: <String>['wizard'], skinnable: true),
  EmojiData('🧚', 'fairy', skinnable: true),
  EmojiData('🧛', 'vampire', skinnable: true),
  EmojiData('🧜', 'mermaid', skinnable: true),
  EmojiData('🧝', 'elf', skinnable: true),
  EmojiData('🧞', 'genie'),
  EmojiData('🧟', 'zombie'),
  EmojiData('💃', 'woman dancing', keywords: <String>['dance'], skinnable: true),
  EmojiData('🕺', 'man dancing', keywords: <String>['dance'], skinnable: true),
  EmojiData('🕴️', 'person in suit levitating'),
];

const List<EmojiData> _animals = <EmojiData>[
  EmojiData('🐶', 'dog face', keywords: <String>['puppy']),
  EmojiData('🐱', 'cat face', keywords: <String>['kitty']),
  EmojiData('🐭', 'mouse face'),
  EmojiData('🐹', 'hamster'),
  EmojiData('🐰', 'rabbit face', keywords: <String>['bunny']),
  EmojiData('🦊', 'fox'),
  EmojiData('🐻', 'bear'),
  EmojiData('🐼', 'panda'),
  EmojiData('🐨', 'koala'),
  EmojiData('🐯', 'tiger face'),
  EmojiData('🦁', 'lion'),
  EmojiData('🐮', 'cow face'),
  EmojiData('🐷', 'pig face'),
  EmojiData('🐸', 'frog'),
  EmojiData('🐵', 'monkey face'),
  EmojiData('🙈', 'see-no-evil monkey'),
  EmojiData('🙉', 'hear-no-evil monkey'),
  EmojiData('🙊', 'speak-no-evil monkey'),
  EmojiData('🐒', 'monkey'),
  EmojiData('🐔', 'chicken'),
  EmojiData('🐧', 'penguin'),
  EmojiData('🐦', 'bird'),
  EmojiData('🐤', 'baby chick'),
  EmojiData('🦆', 'duck'),
  EmojiData('🦅', 'eagle'),
  EmojiData('🦉', 'owl'),
  EmojiData('🦇', 'bat'),
  EmojiData('🐺', 'wolf'),
  EmojiData('🐗', 'boar'),
  EmojiData('🐴', 'horse face'),
  EmojiData('🦄', 'unicorn'),
  EmojiData('🐝', 'honeybee', keywords: <String>['bee']),
  EmojiData('🪲', 'beetle'),
  EmojiData('🐛', 'bug'),
  EmojiData('🦋', 'butterfly'),
  EmojiData('🐌', 'snail'),
  EmojiData('🐞', 'lady beetle', keywords: <String>['ladybug']),
  EmojiData('🐜', 'ant'),
  EmojiData('🪰', 'fly'),
  EmojiData('🪳', 'cockroach'),
  EmojiData('🦗', 'cricket'),
  EmojiData('🕷️', 'spider'),
  EmojiData('🦂', 'scorpion'),
  EmojiData('🐢', 'turtle'),
  EmojiData('🐍', 'snake'),
  EmojiData('🦎', 'lizard'),
  EmojiData('🦖', 'T-Rex', keywords: <String>['dinosaur']),
  EmojiData('🦕', 'sauropod', keywords: <String>['dinosaur']),
  EmojiData('🐙', 'octopus'),
  EmojiData('🦑', 'squid'),
  EmojiData('🦐', 'shrimp'),
  EmojiData('🦞', 'lobster'),
  EmojiData('🐠', 'tropical fish'),
  EmojiData('🐟', 'fish'),
  EmojiData('🐡', 'blowfish'),
  EmojiData('🐬', 'dolphin'),
  EmojiData('🐳', 'spouting whale'),
  EmojiData('🐋', 'whale'),
  EmojiData('🦈', 'shark'),
  EmojiData('🐊', 'crocodile'),
  EmojiData('🐅', 'tiger'),
  EmojiData('🐆', 'leopard'),
  EmojiData('🦓', 'zebra'),
  EmojiData('🦍', 'gorilla'),
  EmojiData('🦧', 'orangutan'),
  EmojiData('🦣', 'mammoth'),
  EmojiData('🐘', 'elephant'),
  EmojiData('🦛', 'hippopotamus'),
  EmojiData('🦏', 'rhinoceros'),
  EmojiData('🐪', 'camel'),
  EmojiData('🐫', 'two-hump camel'),
  EmojiData('🦒', 'giraffe'),
  EmojiData('🦘', 'kangaroo'),
  EmojiData('🐃', 'water buffalo'),
  EmojiData('🐂', 'ox'),
  EmojiData('🐄', 'cow'),
  EmojiData('🐎', 'horse'),
  EmojiData('🐖', 'pig'),
  EmojiData('🐏', 'ram'),
  EmojiData('🐑', 'ewe', keywords: <String>['sheep']),
  EmojiData('🐐', 'goat'),
  EmojiData('🐓', 'rooster'),
  EmojiData('🦃', 'turkey'),
  EmojiData('🦚', 'peacock'),
  EmojiData('🦜', 'parrot'),
  EmojiData('🦢', 'swan'),
  EmojiData('🦩', 'flamingo'),
  EmojiData('🕊️', 'dove', keywords: <String>['peace']),
  EmojiData('🐇', 'rabbit'),
  EmojiData('🦝', 'raccoon'),
  EmojiData('🦨', 'skunk'),
  EmojiData('🦫', 'beaver'),
  EmojiData('🦡', 'badger'),
  EmojiData('🐾', 'paw prints'),
  EmojiData('🌵', 'cactus'),
  EmojiData('🎄', 'Christmas tree'),
  EmojiData('🌲', 'evergreen tree', keywords: <String>['pine']),
  EmojiData('🌳', 'deciduous tree'),
  EmojiData('🌴', 'palm tree'),
  EmojiData('🌱', 'seedling', keywords: <String>['sprout']),
  EmojiData('🌿', 'herb', keywords: <String>['leaf']),
  EmojiData('☘️', 'shamrock'),
  EmojiData('🍀', 'four leaf clover', keywords: <String>['luck']),
  EmojiData('🍁', 'maple leaf'),
  EmojiData('🍂', 'fallen leaf'),
  EmojiData('🍃', 'leaf fluttering in wind'),
  EmojiData('🌸', 'cherry blossom', keywords: <String>['flower']),
  EmojiData('💐', 'bouquet', keywords: <String>['flowers']),
  EmojiData('🌹', 'rose', keywords: <String>['flower']),
  EmojiData('🥀', 'wilted flower'),
  EmojiData('🌺', 'hibiscus'),
  EmojiData('🌻', 'sunflower'),
  EmojiData('🌼', 'blossom', keywords: <String>['flower']),
  EmojiData('🌷', 'tulip'),
  EmojiData('🌾', 'sheaf of rice'),
  EmojiData('🍄', 'mushroom'),
  EmojiData('🌰', 'chestnut'),
];

const List<EmojiData> _food = <EmojiData>[
  EmojiData('🍏', 'green apple'),
  EmojiData('🍎', 'red apple'),
  EmojiData('🍐', 'pear'),
  EmojiData('🍊', 'tangerine', keywords: <String>['orange']),
  EmojiData('🍋', 'lemon'),
  EmojiData('🍌', 'banana'),
  EmojiData('🍉', 'watermelon'),
  EmojiData('🍇', 'grapes'),
  EmojiData('🍓', 'strawberry'),
  EmojiData('🫐', 'blueberries'),
  EmojiData('🍈', 'melon'),
  EmojiData('🍒', 'cherries'),
  EmojiData('🍑', 'peach'),
  EmojiData('🥭', 'mango'),
  EmojiData('🍍', 'pineapple'),
  EmojiData('🥥', 'coconut'),
  EmojiData('🥝', 'kiwi fruit'),
  EmojiData('🍅', 'tomato'),
  EmojiData('🍆', 'eggplant'),
  EmojiData('🥑', 'avocado'),
  EmojiData('🥦', 'broccoli'),
  EmojiData('🥬', 'leafy green', keywords: <String>['lettuce']),
  EmojiData('🥒', 'cucumber'),
  EmojiData('🌶️', 'hot pepper', keywords: <String>['chili']),
  EmojiData('🫑', 'bell pepper'),
  EmojiData('🌽', 'corn'),
  EmojiData('🥕', 'carrot'),
  EmojiData('🫒', 'olive'),
  EmojiData('🧄', 'garlic'),
  EmojiData('🧅', 'onion'),
  EmojiData('🥔', 'potato'),
  EmojiData('🍠', 'roasted sweet potato'),
  EmojiData('🥐', 'croissant'),
  EmojiData('🥯', 'bagel'),
  EmojiData('🍞', 'bread'),
  EmojiData('🥖', 'baguette bread'),
  EmojiData('🥨', 'pretzel'),
  EmojiData('🧀', 'cheese wedge'),
  EmojiData('🥚', 'egg'),
  EmojiData('🍳', 'cooking', keywords: <String>['fried egg']),
  EmojiData('🧈', 'butter'),
  EmojiData('🥞', 'pancakes'),
  EmojiData('🧇', 'waffle'),
  EmojiData('🥓', 'bacon'),
  EmojiData('🥩', 'cut of meat'),
  EmojiData('🍗', 'poultry leg', keywords: <String>['chicken']),
  EmojiData('🍖', 'meat on bone'),
  EmojiData('🌭', 'hot dog'),
  EmojiData('🍔', 'hamburger', keywords: <String>['burger']),
  EmojiData('🍟', 'french fries'),
  EmojiData('🍕', 'pizza'),
  EmojiData('🥪', 'sandwich'),
  EmojiData('🥙', 'stuffed flatbread'),
  EmojiData('🧆', 'falafel'),
  EmojiData('🌮', 'taco'),
  EmojiData('🌯', 'burrito'),
  EmojiData('🫔', 'tamale'),
  EmojiData('🥗', 'green salad'),
  EmojiData('🍿', 'popcorn'),
  EmojiData('🍝', 'spaghetti', keywords: <String>['pasta']),
  EmojiData('🍜', 'steaming bowl', keywords: <String>['noodles', 'ramen']),
  EmojiData('🍲', 'pot of food', keywords: <String>['stew']),
  EmojiData('🍛', 'curry rice'),
  EmojiData('🍣', 'sushi'),
  EmojiData('🍱', 'bento box'),
  EmojiData('🥟', 'dumpling'),
  EmojiData('🍤', 'fried shrimp', keywords: <String>['prawns']),
  EmojiData('🍙', 'rice ball'),
  EmojiData('🍚', 'cooked rice'),
  EmojiData('🍘', 'rice cracker'),
  EmojiData('🍥', 'fish cake'),
  EmojiData('🥠', 'fortune cookie'),
  EmojiData('🥡', 'takeout box'),
  EmojiData('🍢', 'oden'),
  EmojiData('🍡', 'dango'),
  EmojiData('🍧', 'shaved ice'),
  EmojiData('🍨', 'ice cream'),
  EmojiData('🍦', 'soft ice cream'),
  EmojiData('🍩', 'doughnut'),
  EmojiData('🍪', 'cookie'),
  EmojiData('🎂', 'birthday cake'),
  EmojiData('🍰', 'shortcake'),
  EmojiData('🧁', 'cupcake'),
  EmojiData('🥧', 'pie'),
  EmojiData('🍫', 'chocolate bar'),
  EmojiData('🍬', 'candy'),
  EmojiData('🍭', 'lollipop'),
  EmojiData('🍮', 'custard'),
  EmojiData('🍯', 'honey pot'),
  EmojiData('🍼', 'baby bottle'),
  EmojiData('🥛', 'glass of milk'),
  EmojiData('☕', 'hot beverage', keywords: <String>['coffee', 'tea']),
  EmojiData('🫖', 'teapot'),
  EmojiData('🍵', 'teacup without handle'),
  EmojiData('🧋', 'bubble tea'),
  EmojiData('🍶', 'sake'),
  EmojiData('🍺', 'beer mug'),
  EmojiData('🍻', 'clinking beer mugs'),
  EmojiData('🥂', 'clinking glasses', keywords: <String>['toast', 'cheers']),
  EmojiData('🍷', 'wine glass'),
  EmojiData('🥃', 'tumbler glass', keywords: <String>['whiskey']),
  EmojiData('🍸', 'cocktail glass'),
  EmojiData('🍹', 'tropical drink'),
  EmojiData('🧉', 'mate'),
  EmojiData('🍾', 'bottle with popping cork', keywords: <String>['champagne']),
  EmojiData('🧊', 'ice'),
  EmojiData('🥄', 'spoon'),
  EmojiData('🍴', 'fork and knife'),
  EmojiData('🔪', 'kitchen knife', keywords: <String>['cut']),
  EmojiData('🫙', 'jar'),
];

const List<EmojiData> _activities = <EmojiData>[
  EmojiData('⚽', 'soccer ball', keywords: <String>['football']),
  EmojiData('🏀', 'basketball'),
  EmojiData('🏈', 'american football'),
  EmojiData('⚾', 'baseball'),
  EmojiData('🥎', 'softball'),
  EmojiData('🎾', 'tennis'),
  EmojiData('🏐', 'volleyball'),
  EmojiData('🏉', 'rugby football'),
  EmojiData('🥏', 'flying disc'),
  EmojiData('🎱', 'pool 8 ball', keywords: <String>['billiards']),
  EmojiData('🏓', 'ping pong', keywords: <String>['table tennis']),
  EmojiData('🏸', 'badminton'),
  EmojiData('🥊', 'boxing glove'),
  EmojiData('🥋', 'martial arts uniform'),
  EmojiData('🥅', 'goal net'),
  EmojiData('⛳', 'flag in hole', keywords: <String>['golf']),
  EmojiData('⛸️', 'ice skate'),
  EmojiData('🎣', 'fishing pole', keywords: <String>['fishing']),
  EmojiData('🤿', 'diving mask'),
  EmojiData('🎽', 'running shirt'),
  EmojiData('🎿', 'skis'),
  EmojiData('🛷', 'sled'),
  EmojiData('🥌', 'curling stone'),
  EmojiData('🎯', 'direct hit', keywords: <String>['darts', 'target']),
  EmojiData('🪀', 'yo-yo'),
  EmojiData('🪁', 'kite'),
  EmojiData('🎮', 'video game', keywords: <String>['gamepad']),
  EmojiData('🕹️', 'joystick'),
  EmojiData('🎲', 'game die', keywords: <String>['dice']),
  EmojiData('♟️', 'chess pawn'),
  EmojiData('🎰', 'slot machine'),
  EmojiData('🎳', 'bowling'),
  EmojiData('🎴', 'flower playing cards'),
  EmojiData('🃏', 'joker'),
  EmojiData('🀄', 'mahjong red dragon'),
  EmojiData('🎭', 'performing arts', keywords: <String>['theater', 'mask']),
  EmojiData('🎨', 'artist palette', keywords: <String>['painting']),
  EmojiData('🎬', 'clapper board', keywords: <String>['movie', 'film']),
  EmojiData('🎤', 'microphone', keywords: <String>['sing']),
  EmojiData('🎧', 'headphone', keywords: <String>['music']),
  EmojiData('🎼', 'musical score'),
  EmojiData('🎹', 'musical keyboard', keywords: <String>['piano']),
  EmojiData('🥁', 'drum'),
  EmojiData('🎷', 'saxophone'),
  EmojiData('🎺', 'trumpet'),
  EmojiData('🎸', 'guitar'),
  EmojiData('🪕', 'banjo'),
  EmojiData('🎻', 'violin'),
  EmojiData('🎙️', 'studio microphone'),
  EmojiData('🎚️', 'level slider'),
  EmojiData('🎛️', 'control knobs'),
  EmojiData('📻', 'radio'),
  EmojiData('🏆', 'trophy', keywords: <String>['win']),
  EmojiData('🥇', '1st place medal', keywords: <String>['gold']),
  EmojiData('🥈', '2nd place medal', keywords: <String>['silver']),
  EmojiData('🥉', '3rd place medal', keywords: <String>['bronze']),
  EmojiData('🏅', 'sports medal'),
  EmojiData('🎖️', 'military medal'),
  EmojiData('🎗️', 'reminder ribbon'),
  EmojiData('🎟️', 'admission tickets'),
  EmojiData('🎫', 'ticket'),
  EmojiData('🎪', 'circus tent'),
  EmojiData('🤹', 'person juggling', skinnable: true),
  EmojiData('🎥', 'movie camera'),
  EmojiData('📺', 'television'),
  EmojiData('📸', 'camera with flash'),
  EmojiData('📷', 'camera'),
  EmojiData('🎞️', 'film frames'),
  EmojiData('📽️', 'film projector'),
  EmojiData('🔭', 'telescope'),
  EmojiData('🔬', 'microscope'),
  EmojiData('🕯️', 'candle'),
  EmojiData('💡', 'light bulb', keywords: <String>['idea']),
  EmojiData('🔦', 'flashlight'),
  EmojiData('🪔', 'diya lamp'),
  EmojiData('🧨', 'firecracker', keywords: <String>['fireworks']),
  EmojiData('🎉', 'party popper', keywords: <String>['celebration']),
  EmojiData('🎊', 'confetti ball'),
  EmojiData('🎈', 'balloon'),
  EmojiData('🎂', 'birthday cake'),
  EmojiData('🎁', 'wrapped gift', keywords: <String>['present']),
];

const List<EmojiData> _travel = <EmojiData>[
  EmojiData('🌍', 'globe showing Europe-Africa', keywords: <String>['earth', 'world']),
  EmojiData('🌎', 'globe showing Americas'),
  EmojiData('🌏', 'globe showing Asia-Australia'),
  EmojiData('🗺️', 'world map'),
  EmojiData('🧭', 'compass'),
  EmojiData('🏔️', 'snow-capped mountain'),
  EmojiData('⛰️', 'mountain'),
  EmojiData('🌋', 'volcano'),
  EmojiData('🗻', 'mount fuji'),
  EmojiData('🏕️', 'camping'),
  EmojiData('🏖️', 'beach with umbrella'),
  EmojiData('🏜️', 'desert'),
  EmojiData('🏝️', 'desert island'),
  EmojiData('🏞️', 'national park'),
  EmojiData('🏟️', 'stadium'),
  EmojiData('🏛️', 'classical building'),
  EmojiData('🏗️', 'building construction'),
  EmojiData('🧱', 'brick'),
  EmojiData('🪨', 'rock'),
  EmojiData('🪵', 'wood'),
  EmojiData('🛖', 'hut'),
  EmojiData('🏘️', 'houses'),
  EmojiData('🏚️', 'derelict house'),
  EmojiData('🏠', 'house'),
  EmojiData('🏡', 'house with garden'),
  EmojiData('🏢', 'office building'),
  EmojiData('🏣', 'Japanese post office'),
  EmojiData('🏤', 'post office'),
  EmojiData('🏥', 'hospital'),
  EmojiData('🏦', 'bank'),
  EmojiData('🏨', 'hotel'),
  EmojiData('🏩', 'love hotel'),
  EmojiData('🏪', 'convenience store'),
  EmojiData('🏫', 'school'),
  EmojiData('🏬', 'department store'),
  EmojiData('🏭', 'factory'),
  EmojiData('🏯', 'Japanese castle'),
  EmojiData('🏰', 'castle'),
  EmojiData('💒', 'wedding'),
  EmojiData('🗼', 'Tokyo tower'),
  EmojiData('🗽', 'Statue of Liberty'),
  EmojiData('⛪', 'church'),
  EmojiData('🕌', 'mosque'),
  EmojiData('🛕', 'hindu temple'),
  EmojiData('🕍', 'synagogue'),
  EmojiData('⛩️', 'shinto shrine'),
  EmojiData('🕋', 'kaaba'),
  EmojiData('⛲', 'fountain'),
  EmojiData('⛺', 'tent'),
  EmojiData('🌁', 'foggy'),
  EmojiData('🌃', 'night with stars'),
  EmojiData('🏙️', 'cityscape'),
  EmojiData('🌄', 'sunrise over mountains'),
  EmojiData('🌅', 'sunrise'),
  EmojiData('🌆', 'cityscape at dusk'),
  EmojiData('🌇', 'sunset'),
  EmojiData('🌉', 'bridge at night'),
  EmojiData('♨️', 'hot springs'),
  EmojiData('🎠', 'carousel horse'),
  EmojiData('🎡', 'ferris wheel'),
  EmojiData('🎢', 'roller coaster'),
  EmojiData('💈', 'barber pole'),
  EmojiData('🎪', 'circus tent'),
  EmojiData('🚂', 'locomotive', keywords: <String>['train']),
  EmojiData('🚃', 'railway car'),
  EmojiData('🚄', 'high-speed train'),
  EmojiData('🚅', 'bullet train'),
  EmojiData('🚇', 'metro'),
  EmojiData('🚈', 'light rail'),
  EmojiData('🚉', 'station'),
  EmojiData('🚊', 'tram'),
  EmojiData('🚝', 'monorail'),
  EmojiData('🚞', 'mountain railway'),
  EmojiData('✈️', 'airplane', keywords: <String>['flight', 'plane']),
  EmojiData('🛫', 'airplane departure'),
  EmojiData('🛬', 'airplane arrival'),
  EmojiData('🚁', 'helicopter'),
  EmojiData('🚀', 'rocket', keywords: <String>['space']),
  EmojiData('🛸', 'flying saucer', keywords: <String>['ufo']),
  EmojiData('🚢', 'ship', keywords: <String>['boat']),
  EmojiData('⛵', 'sailboat'),
  EmojiData('🛥️', 'motor boat'),
  EmojiData('🚤', 'speedboat'),
  EmojiData('🛳️', 'passenger ship'),
  EmojiData('⚓', 'anchor'),
  EmojiData('🚏', 'bus stop'),
  EmojiData('🚦', 'vertical traffic light'),
  EmojiData('🚧', 'construction'),
  EmojiData('🗿', 'moai'),
  EmojiData('🗾', 'map of Japan'),
];

const List<EmojiData> _objects = <EmojiData>[
  EmojiData('⌚', 'watch'),
  EmojiData('📱', 'mobile phone', keywords: <String>['cellphone']),
  EmojiData('📲', 'mobile phone with arrow'),
  EmojiData('💻', 'laptop', keywords: <String>['computer']),
  EmojiData('⌨️', 'keyboard'),
  EmojiData('🖥️', 'desktop computer'),
  EmojiData('🖨️', 'printer'),
  EmojiData('🖱️', 'computer mouse'),
  EmojiData('🖲️', 'trackball'),
  EmojiData('💽', 'computer disk'),
  EmojiData('💾', 'floppy disk'),
  EmojiData('💿', 'optical disk'),
  EmojiData('📀', 'dvd'),
  EmojiData('🧮', 'abacus'),
  EmojiData('🎥', 'movie camera'),
  EmojiData('🎞️', 'film frames'),
  EmojiData('📽️', 'film projector'),
  EmojiData('🎬', 'clapper board'),
  EmojiData('📺', 'television'),
  EmojiData('📷', 'camera'),
  EmojiData('📸', 'camera with flash'),
  EmojiData('📹', 'video camera'),
  EmojiData('📼', 'videocassette'),
  EmojiData('🔍', 'magnifying glass tilted left', keywords: <String>['search']),
  EmojiData('🔎', 'magnifying glass tilted right'),
  EmojiData('🕯️', 'candle'),
  EmojiData('💡', 'light bulb'),
  EmojiData('🔦', 'flashlight'),
  EmojiData('🏮', 'red paper lantern'),
  EmojiData('🪔', 'diya lamp'),
  EmojiData('📔', 'notebook with decorative cover'),
  EmojiData('📕', 'closed book'),
  EmojiData('📖', 'open book'),
  EmojiData('📗', 'green book'),
  EmojiData('📘', 'blue book'),
  EmojiData('📙', 'orange book'),
  EmojiData('📚', 'books'),
  EmojiData('📓', 'notebook'),
  EmojiData('📒', 'ledger'),
  EmojiData('📃', 'page with curl'),
  EmojiData('📜', 'scroll'),
  EmojiData('📄', 'page facing up'),
  EmojiData('📰', 'newspaper'),
  EmojiData('🗞️', 'rolled-up newspaper'),
  EmojiData('📑', 'bookmark tabs'),
  EmojiData('🔖', 'bookmark'),
  EmojiData('🏷️', 'label'),
  EmojiData('💰', 'money bag'),
  EmojiData('💴', 'yen banknote'),
  EmojiData('💵', 'dollar banknote'),
  EmojiData('💶', 'euro banknote'),
  EmojiData('💷', 'pound banknote'),
  EmojiData('💸', 'money with wings'),
  EmojiData('💳', 'credit card'),
  EmojiData('🧾', 'receipt'),
  EmojiData('✉️', 'envelope', keywords: <String>['mail']),
  EmojiData('📧', 'e-mail'),
  EmojiData('📨', 'incoming envelope'),
  EmojiData('📩', 'envelope with arrow'),
  EmojiData('📤', 'outbox tray'),
  EmojiData('📥', 'inbox tray'),
  EmojiData('📦', 'package', keywords: <String>['box']),
  EmojiData('📫', 'closed mailbox with raised flag'),
  EmojiData('📬', 'open mailbox with raised flag'),
  EmojiData('📮', 'postbox'),
  EmojiData('📝', 'memo', keywords: <String>['note']),
  EmojiData('✏️', 'pencil'),
  EmojiData('✒️', 'black nib'),
  EmojiData('🖊️', 'pen'),
  EmojiData('🖋️', 'fountain pen'),
  EmojiData('🖌️', 'paintbrush'),
  EmojiData('🖍️', 'crayon'),
  EmojiData('📅', 'calendar'),
  EmojiData('📆', 'tear-off calendar'),
  EmojiData('🗒️', 'spiral notepad'),
  EmojiData('🗓️', 'spiral calendar'),
  EmojiData('📇', 'card index'),
  EmojiData('📈', 'chart increasing'),
  EmojiData('📉', 'chart decreasing'),
  EmojiData('📊', 'bar chart'),
  EmojiData('📋', 'clipboard'),
  EmojiData('📌', 'pushpin'),
  EmojiData('📍', 'round pushpin'),
  EmojiData('📎', 'paperclip'),
  EmojiData('🖇️', 'linked paperclips'),
  EmojiData('📏', 'straight ruler'),
  EmojiData('📐', 'triangular ruler'),
  EmojiData('✂️', 'scissors'),
  EmojiData('🗃️', 'card file box'),
  EmojiData('🗄️', 'file cabinet'),
  EmojiData('🗑️', 'wastebasket', keywords: <String>['trash']),
  EmojiData('🔒', 'locked', keywords: <String>['lock']),
  EmojiData('🔓', 'unlocked'),
  EmojiData('🔏', 'locked with pen'),
  EmojiData('🔐', 'locked with key'),
  EmojiData('🔑', 'key'),
  EmojiData('🗝️', 'old key'),
  EmojiData('🔨', 'hammer'),
  EmojiData('🪓', 'axe'),
  EmojiData('⛏️', 'pick'),
  EmojiData('⚒️', 'hammer and pick'),
  EmojiData('🛠️', 'hammer and wrench'),
  EmojiData('🗡️', 'dagger'),
  EmojiData('⚔️', 'crossed swords'),
  EmojiData('🔫', 'water pistol', keywords: <String>['gun']),
  EmojiData('🛡️', 'shield'),
  EmojiData('🔧', 'wrench'),
  EmojiData('🔩', 'nut and bolt'),
  EmojiData('⚙️', 'gear'),
  EmojiData('🗜️', 'clamp'),
  EmojiData('⚖️', 'balance scale'),
  EmojiData('🦯', 'white cane'),
  EmojiData('🔗', 'link'),
  EmojiData('⛓️', 'chains'),
  EmojiData('🧰', 'toolbox'),
  EmojiData('🧲', 'magnet'),
  EmojiData('🪜', 'ladder'),
  EmojiData('⚗️', 'alembic'),
  EmojiData('🧪', 'test tube', keywords: <String>['science']),
  EmojiData('🧫', 'petri dish'),
  EmojiData('🧬', 'dna'),
  EmojiData('🔬', 'microscope'),
  EmojiData('🔭', 'telescope'),
  EmojiData('📡', 'satellite antenna'),
  EmojiData('💉', 'syringe'),
  EmojiData('🩸', 'drop of blood'),
  EmojiData('💊', 'pill'),
  EmojiData('🩹', 'adhesive bandage'),
  EmojiData('🩺', 'stethoscope'),
  EmojiData('🚪', 'door'),
  EmojiData('🛗', 'elevator'),
  EmojiData('🪞', 'mirror'),
  EmojiData('🪟', 'window'),
  EmojiData('🛏️', 'bed'),
  EmojiData('🛋️', 'couch and lamp'),
  EmojiData('🪑', 'chair'),
  EmojiData('🚽', 'toilet'),
  EmojiData('🚿', 'shower'),
  EmojiData('🛁', 'bathtub'),
  EmojiData('🪤', 'mouse trap'),
  EmojiData('🧻', 'roll of paper', keywords: <String>['toilet paper']),
  EmojiData('🧹', 'broom'),
  EmojiData('🧺', 'basket'),
  EmojiData('🧴', 'lotion bottle'),
  EmojiData('🧽', 'sponge'),
  EmojiData('🧯', 'fire extinguisher'),
  EmojiData('🛒', 'shopping cart'),
];

const List<EmojiData> _symbols = <EmojiData>[
  EmojiData('❤️', 'red heart'),
  EmojiData('💯', 'hundred points', keywords: <String>['100', 'perfect']),
  EmojiData('💢', 'anger symbol'),
  EmojiData('💬', 'speech balloon', keywords: <String>['chat', 'message']),
  EmojiData('💭', 'thought balloon'),
  EmojiData('🗯️', 'anger bubble'),
  EmojiData('💤', 'zzz', keywords: <String>['sleep']),
  EmojiData('💦', 'sweat droplets', keywords: <String>['water']),
  EmojiData('💨', 'dashing away', keywords: <String>['smoke', 'run']),
  EmojiData('🕳️', 'hole'),
  EmojiData('💣', 'bomb'),
  EmojiData('💥', 'collision', keywords: <String>['boom']),
  EmojiData('💫', 'dizzy', keywords: <String>['star']),
  EmojiData('🌐', 'globe with meridians'),
  EmojiData('🔞', 'no one under eighteen', keywords: <String>['18']),
  EmojiData('💱', 'currency exchange'),
  EmojiData('💲', 'heavy dollar sign'),
  EmojiData('©️', 'copyright'),
  EmojiData('®️', 'registered'),
  EmojiData('™️', 'trade mark'),
  EmojiData('🔟', 'keycap 10'),
  EmojiData('🔢', 'input numbers'),
  EmojiData('🔤', 'input latin letters'),
  EmojiData('🔡', 'input latin lowercase'),
  EmojiData('🔠', 'input latin uppercase'),
  EmojiData('🔣', 'input symbols'),
  EmojiData('◼️', 'black square'),
  EmojiData('◻️', 'white square'),
  EmojiData('🔲', 'black square button'),
  EmojiData('🔳', 'white square button'),
  EmojiData('🔴', 'red circle'),
  EmojiData('🟠', 'orange circle'),
  EmojiData('🟡', 'yellow circle'),
  EmojiData('🟢', 'green circle'),
  EmojiData('🔵', 'blue circle'),
  EmojiData('🟣', 'purple circle'),
  EmojiData('⚪', 'white circle'),
  EmojiData('⚫', 'black circle'),
  EmojiData('⬛', 'black large square'),
  EmojiData('⬜', 'white large square'),
  EmojiData('🟥', 'red square'),
  EmojiData('🟧', 'orange square'),
  EmojiData('🟨', 'yellow square'),
  EmojiData('🟩', 'green square'),
  EmojiData('🟦', 'blue square'),
  EmojiData('🟪', 'purple square'),
  EmojiData('🟫', 'brown square'),
  EmojiData('⭐', 'star'),
  EmojiData('🌟', 'glowing star', keywords: <String>['sparkle']),
  EmojiData('✨', 'sparkles'),
  EmojiData('⚡', 'high voltage', keywords: <String>['zap', 'electric']),
  EmojiData('🔥', 'fire', keywords: <String>['hot']),
  EmojiData('🌈', 'rainbow'),
  EmojiData('☀️', 'sun', keywords: <String>['sunny']),
  EmojiData('☁️', 'cloud'),
  EmojiData('⛅', 'sun behind cloud'),
  EmojiData('⛈️', 'cloud with lightning and rain'),
  EmojiData('🌤️', 'sun behind small cloud'),
  EmojiData('🌥️', 'sun behind large cloud'),
  EmojiData('🌦️', 'sun behind rain cloud'),
  EmojiData('🌧️', 'cloud with rain'),
  EmojiData('🌨️', 'cloud with snow'),
  EmojiData('🌩️', 'cloud with lightning'),
  EmojiData('🌪️', 'tornado'),
  EmojiData('🌫️', 'fog'),
  EmojiData('🌬️', 'wind face'),
  EmojiData('💧', 'droplet', keywords: <String>['water']),
  EmojiData('💎', 'gem stone', keywords: <String>['diamond']),
  EmojiData('♻️', 'recycle'),
  EmojiData('✅', 'check mark button'),
  EmojiData('❌', 'cross mark'),
  EmojiData('❓', 'question mark', keywords: <String>['?']),
  EmojiData('❗', 'exclamation mark', keywords: <String>['!']),
  EmojiData('➡️', 'right arrow'),
  EmojiData('⬆️', 'up arrow'),
  EmojiData('⬇️', 'down arrow'),
  EmojiData('⬅️', 'left arrow'),
  EmojiData('↗️', 'up-right arrow'),
  EmojiData('↘️', 'down-right arrow'),
  EmojiData('↙️', 'down-left arrow'),
  EmojiData('↖️', 'up-left arrow'),
  EmojiData('🔄', 'counterclockwise arrows button', keywords: <String>['refresh']),
  EmojiData('🔃', 'clockwise vertical arrows'),
  EmojiData('➰', 'curly loop'),
  EmojiData('➿', 'double curly loop'),
  EmojiData('🚫', 'prohibited', keywords: <String>['no']),
  EmojiData('⛔', 'no entry'),
  EmojiData('⚠️', 'warning'),
  EmojiData('🚸', 'children crossing'),
  EmojiData('🔱', 'trident emblem'),
  EmojiData('☯️', 'yin yang'),
  EmojiData('♈', 'Aries'),
  EmojiData('♉', 'Taurus'),
  EmojiData('♊', 'Gemini'),
  EmojiData('♋', 'Cancer'),
  EmojiData('♌', 'Leo'),
  EmojiData('♍', 'Virgo'),
  EmojiData('♎', 'Libra'),
  EmojiData('♏', 'Scorpio'),
  EmojiData('♐', 'Sagittarius'),
  EmojiData('♑', 'Capricorn'),
  EmojiData('♒', 'Aquarius'),
  EmojiData('♓', 'Pisces'),
];

const List<EmojiData> _flags = <EmojiData>[
  EmojiData('🏁', 'chequered flag', keywords: <String>['racing']),
  EmojiData('🚩', 'triangular flag'),
  EmojiData('🎌', 'crossed flags'),
  EmojiData('🏴', 'black flag'),
  EmojiData('🏳️', 'white flag'),
  EmojiData('🇺🇳', 'United Nations'),
  EmojiData('🇦🇫', 'Afghanistan'),
  EmojiData('🇦🇱', 'Albania'),
  EmojiData('🇩🇿', 'Algeria'),
  EmojiData('🇦🇴', 'Angola'),
  EmojiData('🇦🇷', 'Argentina'),
  EmojiData('🇦🇲', 'Armenia'),
  EmojiData('🇦🇺', 'Australia'),
  EmojiData('🇦🇹', 'Austria'),
  EmojiData('🇦🇿', 'Azerbaijan'),
  EmojiData('🇧🇸', 'Bahamas'),
  EmojiData('🇧🇭', 'Bahrain'),
  EmojiData('🇧🇩', 'Bangladesh'),
  EmojiData('🇧🇧', 'Barbados'),
  EmojiData('🇧🇾', 'Belarus'),
  EmojiData('🇧🇪', 'Belgium'),
  EmojiData('🇧🇿', 'Belize'),
  EmojiData('🇧🇯', 'Benin'),
  EmojiData('🇧🇹', 'Bhutan'),
  EmojiData('🇧🇴', 'Bolivia'),
  EmojiData('🇧🇦', 'Bosnia and Herzegovina'),
  EmojiData('🇧🇼', 'Botswana'),
  EmojiData('🇧🇷', 'Brazil'),
  EmojiData('🇧🇳', 'Brunei'),
  EmojiData('🇧🇬', 'Bulgaria'),
  EmojiData('🇧🇫', 'Burkina Faso'),
  EmojiData('🇧🇮', 'Burundi'),
  EmojiData('🇰🇭', 'Cambodia'),
  EmojiData('🇨🇲', 'Cameroon'),
  EmojiData('🇨🇦', 'Canada'),
  EmojiData('🇨🇻', 'Cape Verde'),
  EmojiData('🇨🇫', 'Central African Republic'),
  EmojiData('🇹🇩', 'Chad'),
  EmojiData('🇨🇱', 'Chile'),
  EmojiData('🇨🇳', 'China'),
  EmojiData('🇨🇴', 'Colombia'),
  EmojiData('🇨🇷', 'Costa Rica'),
  EmojiData('🇨🇮', 'Côte d’Ivoire', keywords: <String>['ivory coast']),
  EmojiData('🇭🇷', 'Croatia'),
  EmojiData('🇨🇺', 'Cuba'),
  EmojiData('🇨🇾', 'Cyprus'),
  EmojiData('🇨🇿', 'Czechia', keywords: <String>['czech republic']),
  EmojiData('🇩🇰', 'Denmark'),
  EmojiData('🇩🇯', 'Djibouti'),
  EmojiData('🇩🇴', 'Dominican Republic'),
  EmojiData('🇪🇨', 'Ecuador'),
  EmojiData('🇪🇬', 'Egypt'),
  EmojiData('🇸🇻', 'El Salvador'),
  EmojiData('🇪🇪', 'Estonia'),
  EmojiData('🇪🇹', 'Ethiopia'),
  EmojiData('🇫🇯', 'Fiji'),
  EmojiData('🇫🇮', 'Finland'),
  EmojiData('🇫🇷', 'France'),
  EmojiData('🇬🇦', 'Gabon'),
  EmojiData('🇬🇲', 'Gambia'),
  EmojiData('🇬🇪', 'Georgia'),
  EmojiData('🇩🇪', 'Germany'),
  EmojiData('🇬🇭', 'Ghana'),
  EmojiData('🇬🇷', 'Greece'),
  EmojiData('🇬🇱', 'Greenland'),
  EmojiData('🇬🇹', 'Guatemala'),
  EmojiData('🇬🇳', 'Guinea'),
  EmojiData('🇬🇾', 'Guyana'),
  EmojiData('🇭🇹', 'Haiti'),
  EmojiData('🇭🇳', 'Honduras'),
  EmojiData('🇭🇰', 'Hong Kong'),
  EmojiData('🇭🇺', 'Hungary'),
  EmojiData('🇮🇸', 'Iceland'),
  EmojiData('🇮🇳', 'India'),
  EmojiData('🇮🇩', 'Indonesia'),
  EmojiData('🇮🇷', 'Iran'),
  EmojiData('🇮🇶', 'Iraq'),
  EmojiData('🇮🇪', 'Ireland'),
  EmojiData('🇮🇱', 'Israel'),
  EmojiData('🇮🇹', 'Italy'),
  EmojiData('🇯🇲', 'Jamaica'),
  EmojiData('🇯🇵', 'Japan'),
  EmojiData('🇯🇴', 'Jordan'),
  EmojiData('🇰🇿', 'Kazakhstan'),
  EmojiData('🇰🇪', 'Kenya'),
  EmojiData('🇰🇵', 'North Korea'),
  EmojiData('🇰🇷', 'South Korea'),
  EmojiData('🇰🇼', 'Kuwait'),
  EmojiData('🇰🇬', 'Kyrgyzstan'),
  EmojiData('🇱🇦', 'Laos'),
  EmojiData('🇱🇻', 'Latvia'),
  EmojiData('🇱🇧', 'Lebanon'),
  EmojiData('🇱🇸', 'Lesotho'),
  EmojiData('🇱🇷', 'Liberia'),
  EmojiData('🇱🇾', 'Libya'),
  EmojiData('🇱🇹', 'Lithuania'),
  EmojiData('🇱🇺', 'Luxembourg'),
  EmojiData('🇲🇬', 'Madagascar'),
  EmojiData('🇲🇾', 'Malaysia'),
  EmojiData('🇲🇻', 'Maldives'),
  EmojiData('🇲🇱', 'Mali'),
  EmojiData('🇲🇹', 'Malta'),
  EmojiData('🇲🇷', 'Mauritania'),
  EmojiData('🇲🇺', 'Mauritius'),
  EmojiData('🇲🇽', 'Mexico'),
  EmojiData('🇲🇩', 'Moldova'),
  EmojiData('🇲🇨', 'Monaco'),
  EmojiData('🇲🇳', 'Mongolia'),
  EmojiData('🇲🇪', 'Montenegro'),
  EmojiData('🇲🇦', 'Morocco'),
  EmojiData('🇲🇿', 'Mozambique'),
  EmojiData('🇲🇲', 'Myanmar'),
  EmojiData('🇳🇦', 'Namibia'),
  EmojiData('🇳🇵', 'Nepal'),
  EmojiData('🇳🇱', 'Netherlands'),
  EmojiData('🇳🇿', 'New Zealand'),
  EmojiData('🇳🇮', 'Nicaragua'),
  EmojiData('🇳🇪', 'Niger'),
  EmojiData('🇳🇬', 'Nigeria'),
  EmojiData('🇳🇴', 'Norway'),
  EmojiData('🇴🇲', 'Oman'),
  EmojiData('🇵🇰', 'Pakistan'),
  EmojiData('🇵🇸', 'Palestine'),
  EmojiData('🇵🇦', 'Panama'),
  EmojiData('🇵🇬', 'Papua New Guinea'),
  EmojiData('🇵🇾', 'Paraguay'),
  EmojiData('🇵🇪', 'Peru'),
  EmojiData('🇵🇭', 'Philippines'),
  EmojiData('🇵🇱', 'Poland'),
  EmojiData('🇵🇹', 'Portugal'),
  EmojiData('🇵🇷', 'Puerto Rico'),
  EmojiData('🇶🇦', 'Qatar'),
  EmojiData('🇨🇬', 'Republic of the Congo'),
  EmojiData('🇷🇴', 'Romania'),
  EmojiData('🇷🇺', 'Russia'),
  EmojiData('🇷🇼', 'Rwanda'),
  EmojiData('🇸🇦', 'Saudi Arabia'),
  EmojiData('🇸🇳', 'Senegal'),
  EmojiData('🇷🇸', 'Serbia'),
  EmojiData('🇸🇬', 'Singapore'),
  EmojiData('🇸🇰', 'Slovakia'),
  EmojiData('🇸🇮', 'Slovenia'),
  EmojiData('🇸🇴', 'Somalia'),
  EmojiData('🇿🇦', 'South Africa'),
  EmojiData('🇪🇸', 'Spain'),
  EmojiData('🇱🇰', 'Sri Lanka'),
  EmojiData('🇸🇩', 'Sudan'),
  EmojiData('🇸🇷', 'Suriname'),
  EmojiData('🇸🇿', 'Eswatini', keywords: <String>['swaziland']),
  EmojiData('🇸🇪', 'Sweden'),
  EmojiData('🇨🇭', 'Switzerland'),
  EmojiData('🇸🇾', 'Syria'),
  EmojiData('🇹🇼', 'Taiwan'),
  EmojiData('🇹🇯', 'Tajikistan'),
  EmojiData('🇹🇿', 'Tanzania'),
  EmojiData('🇹🇭', 'Thailand'),
  EmojiData('🇹🇬', 'Togo'),
  EmojiData('🇹🇹', 'Trinidad and Tobago'),
  EmojiData('🇹🇳', 'Tunisia'),
  EmojiData('🇹🇷', 'Turkey'),
  EmojiData('🇹🇲', 'Turkmenistan'),
  EmojiData('🇹🇻', 'Tuvalu'),
  EmojiData('🇺🇬', 'Uganda'),
  EmojiData('🇺🇦', 'Ukraine'),
  EmojiData('🇦🇪', 'United Arab Emirates'),
  EmojiData('🇬🇧', 'United Kingdom', keywords: <String>['uk', 'britain']),
  EmojiData('🇺🇸', 'United States', keywords: <String>['usa', 'america']),
  EmojiData('🇺🇾', 'Uruguay'),
  EmojiData('🇺🇿', 'Uzbekistan'),
  EmojiData('🇻🇪', 'Venezuela'),
  EmojiData('🇻🇳', 'Vietnam'),
  EmojiData('🇾🇪', 'Yemen'),
  EmojiData('🇿🇲', 'Zambia'),
  EmojiData('🇿🇼', 'Zimbabwe'),
];

/// All emojis across every category, flattened for search.
const List<EmojiData> allEmojiData = <EmojiData>[
  ..._smileys,
  ..._gestures,
  ..._animals,
  ..._food,
  ..._activities,
  ..._travel,
  ..._objects,
  ..._symbols,
  ..._flags,
];

/// Unicode skin-tone modifiers, ordered light to dark (empty string = none).
const List<String> skinTones = <String>[
  '',
  '\u{1F3FB}',
  '\u{1F3FC}',
  '\u{1F3FD}',
  '\u{1F3FE}',
  '\u{1F3FF}',
];
