/// A human-readable language option for translation targets.
class Language {
  const Language(this.code, this.name);

  /// ISO 639-1-ish code (informational; the edge function uses [name]).
  final String code;

  /// English display name, e.g. "French".
  final String name;
}

/// The languages offered by the chat translator, in English name order.
///
/// Covers the major world languages (translation targets sent to the AI edge
/// function by name).
const List<Language> worldLanguages = <Language>[
  Language('af', 'Afrikaans'),
  Language('sq', 'Albanian'),
  Language('am', 'Amharic'),
  Language('ar', 'Arabic'),
  Language('hy', 'Armenian'),
  Language('az', 'Azerbaijani'),
  Language('eu', 'Basque'),
  Language('be', 'Belarusian'),
  Language('bn', 'Bengali'),
  Language('bs', 'Bosnian'),
  Language('bg', 'Bulgarian'),
  Language('my', 'Burmese'),
  Language('ca', 'Catalan'),
  Language('ceb', 'Cebuano'),
  Language('zh-CN', 'Chinese (Simplified)'),
  Language('zh-TW', 'Chinese (Traditional)'),
  Language('co', 'Corsican'),
  Language('hr', 'Croatian'),
  Language('cs', 'Czech'),
  Language('da', 'Danish'),
  Language('nl', 'Dutch'),
  Language('en', 'English'),
  Language('eo', 'Esperanto'),
  Language('et', 'Estonian'),
  Language('fi', 'Finnish'),
  Language('fil', 'Filipino'),
  Language('fr', 'French'),
  Language('gl', 'Galician'),
  Language('ka', 'Georgian'),
  Language('de', 'German'),
  Language('el', 'Greek'),
  Language('gu', 'Gujarati'),
  Language('ht', 'Haitian Creole'),
  Language('ha', 'Hausa'),
  Language('haw', 'Hawaiian'),
  Language('he', 'Hebrew'),
  Language('hi', 'Hindi'),
  Language('hmn', 'Hmong'),
  Language('hu', 'Hungarian'),
  Language('is', 'Icelandic'),
  Language('ig', 'Igbo'),
  Language('id', 'Indonesian'),
  Language('ga', 'Irish'),
  Language('it', 'Italian'),
  Language('ja', 'Japanese'),
  Language('jv', 'Javanese'),
  Language('kn', 'Kannada'),
  Language('kk', 'Kazakh'),
  Language('km', 'Khmer'),
  Language('ko', 'Korean'),
  Language('ku', 'Kurdish'),
  Language('ky', 'Kyrgyz'),
  Language('lo', 'Lao'),
  Language('la', 'Latin'),
  Language('lv', 'Latvian'),
  Language('lt', 'Lithuanian'),
  Language('lb', 'Luxembourgish'),
  Language('mk', 'Macedonian'),
  Language('mg', 'Malagasy'),
  Language('ms', 'Malay'),
  Language('ml', 'Malayalam'),
  Language('mt', 'Maltese'),
  Language('mi', 'Maori'),
  Language('mr', 'Marathi'),
  Language('mn', 'Mongolian'),
  Language('ne', 'Nepali'),
  Language('no', 'Norwegian'),
  Language('or', 'Odia'),
  Language('ps', 'Pashto'),
  Language('fa', 'Persian'),
  Language('pl', 'Polish'),
  Language('pt', 'Portuguese'),
  Language('pa', 'Punjabi'),
  Language('ro', 'Romanian'),
  Language('ru', 'Russian'),
  Language('sm', 'Samoan'),
  Language('gd', 'Scottish Gaelic'),
  Language('sr', 'Serbian'),
  Language('sn', 'Shona'),
  Language('sd', 'Sindhi'),
  Language('si', 'Sinhala'),
  Language('sk', 'Slovak'),
  Language('sl', 'Slovenian'),
  Language('so', 'Somali'),
  Language('es', 'Spanish'),
  Language('su', 'Sundanese'),
  Language('sw', 'Swahili'),
  Language('sv', 'Swedish'),
  Language('tg', 'Tajik'),
  Language('ta', 'Tamil'),
  Language('tt', 'Tatar'),
  Language('te', 'Telugu'),
  Language('th', 'Thai'),
  Language('tr', 'Turkish'),
  Language('tk', 'Turkmen'),
  Language('uk', 'Ukrainian'),
  Language('ur', 'Urdu'),
  Language('ug', 'Uyghur'),
  Language('uz', 'Uzbek'),
  Language('vi', 'Vietnamese'),
  Language('cy', 'Welsh'),
  Language('xh', 'Xhosa'),
  Language('yi', 'Yiddish'),
  Language('yo', 'Yoruba'),
  Language('zu', 'Zulu'),
];
